spring:
  main:
    web-application-type: servlet
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/cal365
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8080